### ISSUE TITLE
Bug: Dragging Sounds

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#1]
Using this on sound tracks within playlists, it selects all tracks within the playlist automatically, but when dragging them to another playlist, it only moves the one you had your mouse on.

After that, it locks up again until you swap tabs like before.

FTC done
MDS 1.0.5
5e 1.6.3
Foundry 9.269

**Comment by ironmonk88** [comment]
I believe this was fixed in the last release?
If it wasn't please re-open the ticket.
