### ISSUE TITLE
[BUG] Selection colour for 2nd+ document delayed til mouseup

### ISSUE THREAD

**Issue by esheyw** [ironmonk88/multiple-document-selection#10]
Not 100% sure if this is bug, design decision, or core limitation, but I'm hoping it's a bug:

With no documents selected, the orange highlight on the first document is applied after the selection interval set in settings. With at least one document so selected, any subsequent selections aren't visually confirmed until the click is released. This leads to a lot of holding longer than necessary to be sure I got the thing. It'd be great if every selection worked like the first in this respect.

**Comment by ironmonk88** [comment]
There's not much I can do about this, as Foundry has set the activation to be on click, not mouse up or mouse down.

**Comment by ironmonk88** [comment]
I had a second look at it, and I think I can fake it.

**Comment by esheyw** [comment]
Hey, been a while since I've had some time to play around with this, but whatever you've done in the meantime worked. Feels much better to use now, thanks.
