### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#15]
Errors keep occurring when opening any folders in my PF2e world on Forge (not happening on the app for me); doesn't actually seem to be affecting performance.

![image](https://user-images.githubusercontent.com/99844555/216735868-decd4693-f051-439d-926a-91197074d0a9.png)

Foundry 10.291
PF2 4.6.8
MDS 10.2
FTC ✔️ 
Forge
Chrome 109.0.5414.120

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
