### ISSUE TITLE
[BUG] Tile Templates Directory

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#17]
Seems to have stopped working here at some point. Its only moving one template at a time.

https://user-images.githubusercontent.com/99844555/230280303-0ff1691e-c437-4f28-8965-808867d09d2f.mp4

MATT 10.12
Foundry 10.291
MDS 10.2
FTC ✔️

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
