### ISSUE TITLE
Compendium/Folder Compatibility

### ISSUE THREAD

**Issue by BarovianBadass** [ironmonk88/multiple-document-selection#18]
This would be very helpful for organizing compendiums and selecting entire folders. Right now, it only works with the regular sidebar directories on individual entities (I'm not sure if that is the correct terminology, but it's what I'm going with). If we could select multiple folders and move them at once, it would be great. And to be able to move/import multiple entities in a compendium would be extremely useful.

**Comment by BarovianBadass** [comment]
Sorry. I thought I had it in the right place.

**Comment by ironmonk88** [comment]
Should be added to the latest version.
