### ISSUE TITLE
[BUG] Configure Ownership not working

### ISSUE THREAD

**Issue by MMDaemon** [ironmonk88/multiple-document-selection#19]
Selecting multiple Journal Entries and then right clicking them and selecting the **Configure Ownership** option does not open a dialoge and gives the following error on the console:
```
TypeError: An error occurred while rendering MultipleDocumentOwnershipConfig 52. this.document.getFlag is not a function
[No packages detected]
    at MultipleDocumentOwnershipConfig._getHeaderButtons (foundry.js:7177:72)
    at MultipleDocumentOwnershipConfig._renderOuter (foundry.js:5902:27)
    at MultipleDocumentOwnershipConfig._renderOuter (foundry.js:7089:30)
    at MultipleDocumentOwnershipConfig._render (foundry.js:5802:27)
    at async MultipleDocumentOwnershipConfig._render (foundry.js:6503:5)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5744
Promise.catch (async)
render @ foundry.js:5742
render @ foundry.js:7082
ownershipDialog @ multiple-document-selection.js:598
callback @ multiple-document-selection.js:305
#onClickItem @ foundry.js:64715
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**To Reproduce**
1. Select multiple journal entries
2. Right click one of them
3. Select **Configure Ownership**

**Expected behavior**
It should be opening a dialogue to configure the ownership of selected entries

**Please complete as much of the following information as possible:**
 - Browser: Foundry Virtual Tabletop application
 - Foundry Version: 11.305
 - System: Simple Worldbuilding
 - Module Version: 11.01
 - Are there any errors in the console: see above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No

**Additional context**
I have the following Modules active:
Advanced Macros v2.0.2
DF Settings Clarity v3.3.0
Dice So nice! v4.6.8
Dice Tray v1.5.3
Foundry VTT Content Parser v0.2.50
Levels v4.1.2
libWrapper v1.12.12.1
Monk's Active tile Triggers v11.01
Monk's Enhanced Journal v11.03
Monk's Scene Navigation v11.01
Monk's Token Bar v11.01
Monk's Wall Enhancement v11.01
Multiple Document Selection v11.01
PopOut! v2.14
Simple Calendar v2.3.13
SmallTime v1.16.6
socketLib v1.0.13
Tokenizer v4.2.3
Wall Height v5.0.2

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
