### ISSUE TITLE
Conflict Warning: Monk's Scene Navigation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#3]
You're probably aware of it; just opening in case.

Upon selecting a scene with it.

[W] libWrapper: Potential conflict detected between module Multiple Document Selection and module Monk's Scene Navigation.
Module multiple-document-selection did not chain the wrapper for 'SceneDirectory.prototype._onClickDocumentName'. libWrapper-notifications.js:89:5

**Comment by ironmonk88** [comment]
This was patched in the last relelase.
