### ISSUE TITLE
Right Clicking for a context menu throws an error

### ISSUE THREAD

**Issue by bklick** [ironmonk88/multiple-document-selection#4]
![image](https://user-images.githubusercontent.com/3947702/185048844-959aa18e-4c02-4a5c-b676-1c0737867be1.png)

I think this is a mod conflict with Better RollTables, but I am not entirely sure.

**Comment by ironmonk88** [comment]
I believe this one was already fixed?  If it hasn't been let me know and I'll investigate further.
