### ISSUE TITLE
Bug: Highlight Select on Scenes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#5]
![image](https://user-images.githubusercontent.com/99844555/186994768-4bc7a7fe-cbe3-4cc3-a0f0-538c8a5da4e6.png)
The highlight is behind the scene preview image, and is barely noticable. 

Foundry 9.269
DnD 5e 1.6.3
MDS 1.0.6
FTC ✅

**Comment by ironmonk88** [comment]
Is this still an issue?  I may have fixed this in the last patch.

**Comment by Crowguard** [comment]
Yep. Its fixed in the latest one. 
![image](https://user-images.githubusercontent.com/99844555/201489824-339ab5b5-35ed-4d79-aa7a-8d210a612333.png)
