### ISSUE TITLE
Bug?: No longer moving all documents

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#6]
It's only moving the one the cursor is selecting again. No errors.

Tested on 9.269 & 9.280. It does work on v10 strangely enough.
Also tried PF2e on both v9s, same issue.
![image](https://user-images.githubusercontent.com/99844555/188248917-e9b72edb-6b22-4c9d-beb2-6860e92e656b.png)

**Comment by ironmonk88** [comment]
Is this still an issue?  I lost my v9 testing environment.

**Comment by Crowguard** [comment]
I don't have a v9 either anymore. It doesn't seem to be a problem anymore in v10.

**Comment by Zalmute** [comment]
it is still an issue with v 9

**Comment by ironmonk88** [comment]
Closing this as MDS is only being actively developed for v11.
