### ISSUE TITLE
Compatibility with the DSA/TDE System

### ISSUE THREAD

**Issue by vt-tom** [ironmonk88/multiple-document-selection#7]
**Is your feature request related to a problem? Please describe.**
In the Das schwarze Auge/The dark Eye 5th Edition System, i cant see what is marked. Maybe it is possible to adjust the colors of the marked documents? Or some better design elements to identy them?

**Additional context**
![grafik](https://user-images.githubusercontent.com/80099175/190922777-c08b796a-4c92-41ed-a747-b1462afc975a.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
