### ISSUE TITLE
Feature Request: Macro Directory Integration

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/multiple-document-selection#8]
Doesn't currently work in the macro directory; it would be extremely helpful for getting rid of these MATT macros I do for people and then forget to label.
![image](https://user-images.githubusercontent.com/99844555/192664910-f48ed919-ba40-4920-b002-0555dd8a971e.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
