### ISSUE TITLE
Bug: clicking folders exits selection mode

### ISSUE THREAD

**Issue by shemetz** [ironmonk88/multiple-document-selection#9]
If I want to e.g. move many items from 3 different directories into a 4th directory, this module only lets me do it one folder at a time.  I would like the ability to select all documents in one folder, open a second folder, select several documents from there, and then drag them all somewhere.  However, clicking on a folder to open it will undo all selections currently.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
